### ISSUE TITLE
העתקה מפלקסי

### ISSUE THREAD

**Issue by Derpy666** [xliel/xliel-db#2]
יגנב! גנבת תחבילה מפלקסי, הוא יהרוג אותך!!!
אה ואני מעוניין להזמין אוכל
תביא לי מרתף
עם אמא של ליאל בתוכו
ואני רוצה לקחת את זה בשקית אטומה
תודה
הכסף על הדלפק
תהנה!
יום עסקים שמח!

**Comment by AllRun1** [comment]
אני מעוניין להזמין המבורגר עם ליאל בתוכו
